version: "3.1"
services:
 web:
     build: ./web
     environment:
       - APACHE_RUN_USER=#1000
     volumes:
       - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
     ports:
       - 8080:80
     working_dir: ${APP_PATH_CONTAINER}

 db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: qzwxec123
      POSTGRES_DB: micro_chat
    restart: always


 adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080

 composer:
    image: composer:1.8
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command:  composer install
